default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: padel_live_development
    username: bidobidobae
    password: Wh1t3rfl!
    migration_path: db/migrate

test:
  primary:
    <<: *default
    database: padel_live_test
    migration_path: db/migrate

production:
  primary: &primary_production
    <<: *default
    database: padel_live_production
    username: bidobidobae
    password: Wh1t3rfl!
    migration_path: db/migrate

  cache:
    <<: *primary_production
    database: padel_live_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: padel_live_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: padel_live_production_cable
    migrations_paths: db/cable_migrate

